### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by dzung042** [maelstrom-cms/odin#1] opened 2019-10-04 04:47 UTC

**Comment by dzung042** [comment] 2019-10-04 04:48
I just deploy this app require(): Failed opening required '/var/www/html/odin/vendor/autoload.php, can you tell me how to deploy it? thank you

**Comment by OwenMelbz** [comment] 2019-10-04 06:09
hi,

Sorry that’s a very big question and depends on so many factors.

As it’s a Laravel project - you just deploy it like any other Laravel project.

If you’re unfamiliar with how to do that, there’s loads of tutorials online - you need to pick one that matches your server setup: https://www.google.com/search?q=how+to+deploy+laravel+project

The error you got was because you haven’t installed composer dependencies.

I’m gonna close this issue as it’s not a bug just a support request.

**Closed by OwenMelbz** 2019-10-04 06:09 UTC
