### ISSUE TITLE
Notification via Telegram

### ISSUE THREAD

**Issue by Peter9936** [maelstrom-cms/odin#29] opened 2020-07-25 17:41 UTC
Hi,

Would it be able to get notification via Telegram instead of email?

**Comment by OwenMelbz** [comment] 2020-07-26 15:34
Hi,

If you're willing to submit a PR then we'd consider it.

If not then it's not something we'd be looking to add as our business doesn't use it.

Will close this issue as it's not a bug :)

**Closed** 2020-07-26 15:41 UTC
