### ISSUE TITLE
Sample .sql?

### ISSUE THREAD

**Issue by firstchair** [maelstrom-cms/odin#12] opened 2019-10-22 14:09 UTC
Cool project, looks very intresting.
Do you maybe have a sample .sql? Cant get it to work...

**Comment by OwenMelbz** [comment] 2019-10-22 14:26
Hi,

What can you not get to work? Are there any errors or anything.

I'm afraid just sending an .sql dump won't really work as it requires sequences of events, and caching for various things which the app handles, so a database is only 1 pieces of the puzzle.

I'll happily try help out get it installed though.

**Comment by firstchair** [comment] 2019-10-22 15:05
Thanks for the quick reply :-)

Im getting this error:
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'odin.users' doesn't exist (SQL: select * from `users` where `id` = 0 limit 1)

I made a database but maybe its not connecting right...

**Comment by firstchair** [comment] 2019-10-22 15:34
Need to do php artisan migrate to let it work...
I'm not that familiar with laravel projects... But for sure we're going to give it a try 😀

**Comment by OwenMelbz** [comment] 2019-10-22 17:33
Ah yes! That will do it!

Incase you haven't already a `npm install` and `npm run dev` will probably get the CSS working if it's missing that.

I think you'll need to setup the `.env` file as well and ideally use `redis` for the caching as I believe it uses tagged caches at some points.

I'm just going to close this issue now as it's not a bug as such, but will try respond to any more questions you've got.

**Closed by OwenMelbz** 2019-10-22 17:33 UTC
