### ISSUE TITLE
How add monitors by api , sql insert or cli

### ISSUE THREAD

**Issue by letonphat1988** [maelstrom-cms/odin#44] opened 2020-12-26 02:18 UTC
Hi,
Could we add monitors by cli/sql/restapi from remote?

**Comment by OwenMelbz** [comment] 2020-12-29 16:27
Hi,

There's no reason why not. Feel free to contribute the feature and we can look at potentially merging :)

I'm gonna close this for now as it's not a bug report.

Thanks

**Closed by OwenMelbz** 2020-12-29 16:27 UTC
